export const INCREMENT_COUNTER = 'INCREMENT_COUNTER';
export const DECREMENT_COUNTER = 'DECREMENT_COUNTER';

export const ADD_SELECTED_GLASS = 'ADD_SELECTED_GLASS';
export const REMOVE_SELECTED_GLASS = 'REMOVE_SELECTED_GLASS';
export const LOGIN = 'LOGIN';
export const EMAIL_UPDATED = 'EMAIL_UPDATED';
export const UPDATE_TOKEN = 'UPDATE_TOKEN';
export const USER_CREATED = 'USER_CREATED';
export const VALIDATE_USERNAME = 'VALIDATE_USERNAME';