export const INCREMENT_COUNTER = 'INCREMENT_COUNTER';
export const DECREMENT_COUNTER = 'DECREMENT_COUNTER';

export const SYNC_ADDRESS = 'SYNC_ADDRESS';
export const UPDATE_PERSONAL_INFO = 'UPDATE_PERSONAL_INFO';
export const UPDATE_SPOUSE_INFO = 'UPDATE_SPOUSE_INFO';
export const UPDATE_DEPENDENT_INFO = 'UPDATE_DEPENDENT_INFO';
export const UPDATE_EMPLOYMENT_INFO = 'UPDATE_EMPLOYMENT_INFO';